[package]
name = "avl-tree-rust"
version = "2.1.2"
edition = "2021"

[dependencies]
napi = { version = "3.11.0", default-features = false, features = ["dyn-symbols", "napi4"] }
napi-derive = "3.6.0"

[build-dependencies]
napi-build = "2.3.2"

[dev-dependencies]
criterion = "0.8.2"
proptest = "1.11.0"

[lib]
crate-type = ["cdylib", "rlib"]

[[bench]]
name = "avl_tree"
harness = false

[profile.release]
codegen-units = 1
lto = "thin"
strip = "symbols"
