/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A Node.js AVL tree with signed 32-bit integer keys and string values. */
export declare class AvlTree {
  /** Creates an empty tree in constant time. */
  constructor()
  /**
   * Inserts a key/value pair, replacing the value when the key already exists.
   *
   * Runs in `O(log n)` time.
   */
  insert(key: number, value: string): void
  /**
   * Returns the value for `key`, or `null` in JavaScript when absent.
   *
   * Runs in `O(log n)` time.
   */
  find(key: number): string | null
  /**
   * Removes `key` and returns its value, or `null` in JavaScript when absent.
   *
   * Runs in `O(log n)` time.
   */
  remove(key: number): string | null
  /** Reports whether `key` exists in `O(log n)` time. */
  has(key: number): boolean
  /** Returns the legacy in-order debug representation in `O(n)` time. */
  dump(): string
}
export type AVLTree = AvlTree
